---
driver:
  name: ec2
  region: eu-central-1
  instance_type: t2.micro
  aws_ssh_key_id: frankfurtkeypair
  security_group_ids: ['open']
  tags:
    Name: HTTP Platform
    Service: Infrastructure
    Environment: Test
    Fund: 103010
    Org: 60412
    Department: Systems Engineering

#driver:
  #name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.8.12
  install_strategy: once
  attributes:
    chef-vault:
      databags_fallback: true
    se_baseline:
      chef_client_version: '14.8.12'
      configure_monitoring: false
    nix_baseline:
      chef_client_version: '14.8.12'
      configure_update: false
      hostname: 'funny.business'
    http_platform:
      admin_email: 'fake-it@make-it'
      apache:
        install_test_suite: true
      cert:
        organization: 'fake_org'
        org_unit: 'fake_unit'
      www:
        additional_aliases: 
          django.logchart.com:
            log_level: 'info'
          funny.business:
            log_level: 'info'
        remove_default_index: false
        create_default_index: true
    django_platform:
      #configure_postgres: true
      django_is_system_user: false

verifier:
  name: inspec

# Every bento box supported by Chef 14
platforms:
  - name: ubuntu-18.04
#    driver:
#      network:
#        - ["forwarded_port", {guest: 80, host: 8080, host_ip: "localhost"}]
#        - ["forwarded_port", {guest: 443, host: 8043, host_ip: "localhost"}]
#  - name: ubuntu-16.04
#    driver:
#      network:
#        - ["forwarded_port", {guest: 80, host: 9080, host_ip: "localhost"}]
#        - ["forwarded_port", {guest: 443, host: 9043, host_ip: "localhost"}]
#  - name: ubuntu-16.04-i386
#  - name: ubuntu-14.04
#  - name: ubuntu-14.04-i386
#  - name: debian-9.5
#  - name: debian-9.5-i386
#  - name: debian-8.11
#  - name: debian-8.11-i386
  - name: centos-7
#    driver:
#      network:
#        - ["forwarded_port", {guest: 80, host: 8180, host_ip: "localhost"}]
#        - ["forwarded_port", {guest: 443, host: 8143, host_ip: "localhost"}]
#  - name: centos-7.5
#    driver:
#      network:
#        - ["forwarded_port", {guest: 80, host: 9180, host_ip: "localhost"}]
#        - ["forwarded_port", {guest: 443, host: 9143, host_ip: "localhost"}]
#  - name: centos-6.10
#  - name: centos-6.10-i386
#  - name: centos-5.11
#  - name: centos-5.11-i386
#  - name: oracle-7.5
#  - name: oracle-6.10
#  - name: oracle-6.10-i386
#  - name: oracle-5.11
#  - name: oracle-5.11-i386
#  - name: fedora-28
#  - name: fedora-27
#  - name: gbailey/amzn2 # 2018.11
#  - name: stakahashi/amazonlinux2 # 2017.12
#  - name: realreadme/amazon2016.09
#  - name: opensuse-leap-15.0
#  - name: opensuse-leap-42.3
#  - name: freebsd-12.0
#  - name: freebsd-12.0-i386
#  - name: freebsd-11.2
#  - name: freebsd-11.2-i386
#  - name: freebsd-10.4
#  - name: freebsd-10.4-i386
#  - name: mwrock/Windows2016
#    transport:
#      name: winrm
#  - name: a-mcf/Win2012R2-WMF5-min
#    transport:
#      name: winrm
#  - name: salesforce/server2008r2
#    transport:
#      name: winrm

suites:
#  - name: account
#    run_list:
#      - recipe[se-nix-baseline::default]
#      - recipe[account_site::default]
#    data_bags_path: "test/data_bags"
#    verifier:
#      inspec_tests:
#        - test/integration/default
#        - test/integration/account
#    attributes:
#    includes:
#      - ubuntu-16.04
#      - centos-7.5
  - name: faculty
    run_list:
      #- recipe[se-nix-baseline::default]
      # - recipe[faculty_site::default]
      - recipe[django-tutorial::default]
    data_bags_path: "test/data_bags"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/faculty
    attributes:
    includes:
      - ubuntu-18.04
      - centos-7
